version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/talkable-docs

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ./venv

      - run:
          name: Build documentation
          command: venv/bin/sphinx-build -nW -b html -d build/doctrees source build/html
