version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6

    working_directory: ~/talkable-docs

    branches:
      ignore:
        - gh-pages
        - /.*-gh-pages/

    steps:
      - run:
          name: Display Versions
          command: |
            function extract_version() { perl -pe 'if(($v)=/([0-9]+([.][0-9]+)+)/){print"$v\n";exit}$_=""' ; }
            echo Python $(python3 --version | extract_version)
            echo Ruby $(ruby --version | extract_version)
            echo RubyGems $(gem --version | extract_version)
            echo Bundler $(bundle --version | extract_version)
            echo $(pwd)

      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.5/dist-packages
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements.txt" }}
            - v2-dependencies
      - run:
          name: Install Python Dependencies
          command: |
            python3 < <(curl -s https://bootstrap.pypa.io/get-pip.py)
            pip install -r requirements.txt
      - save_cache:
          key: v2-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - "~/.cache/pip"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.5/dist-packages"
      - run:
          name: Bundle Install
          command: bundle install

      - run:
          name: Build documentation
          command: rake test
