version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6

    working_directory: ~/talkable-docs

    branches:
      ignore:
        - gh-pages
        - /.*-gh-pages/

    steps:
      - checkout

      - run:
          name: Display Versions
          command: |
            function extract_version() { perl -pe 'if(($v)=/([0-9]+([.][0-9]+)+)/){print"$v\n";exit}$_=""' ; }
            echo Python $(python --version | extract_version)
            echo Ruby $(ruby --version | extract_version)
            echo RubyGems $(gem --version | extract_version)
            echo Bundler $(bundle --version | extract_version)
            echo $(pwd)

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ./venv

      - run:
          name: Build documentation
          command: venv/bin/sphinx-build -nW -b html -d build/doctrees source build/html
